weights: yolov5m.pt
cfg: ''
data: /content/gdrive/MyDrive/project_VeP/training_dataset/data.yaml
hyp: yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 250
batch_size: 64
imgsz: 512
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /content/gdrive/MyDrive/project_VeP/training_results/
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /content/gdrive/MyDrive/project_VeP/training_results/exp
